using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using WorkOrderFlow.Web.Models;

namespace WorkOrderFlow.Web.Services;

public class QuotePdfService
{
    public byte[] Generate(Quote quote)
    {
        var customer = quote.Customer;
        var total = quote.LaborCost + quote.PartsCost - quote.Discount;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header()
                    .Column(column =>
                    {
                        column.Item().Text("WorkOrderFlow")
                            .FontSize(24)
                            .Bold();

                        column.Item().Text("Quote / Price Offer")
                            .FontSize(14)
                            .FontColor(Colors.Grey.Darken2);

                        column.Item().PaddingTop(10).LineHorizontal(1);
                    });

                page.Content()
                    .PaddingVertical(20)
                    .Column(column =>
                    {
                        column.Spacing(15);

                        column.Item().Row(row =>
                        {
                            row.RelativeItem().Column(left =>
                            {
                                left.Item().Text("Customer").Bold();
                                left.Item().Text(customer?.FullName ?? "-");

                                if (!string.IsNullOrWhiteSpace(customer?.CompanyName))
                                    left.Item().Text(customer.CompanyName);

                                if (!string.IsNullOrWhiteSpace(customer?.Phone))
                                    left.Item().Text(customer.Phone);

                                if (!string.IsNullOrWhiteSpace(customer?.Email))
                                    left.Item().Text(customer.Email);
                            });

                            row.RelativeItem().Column(right =>
                            {
                                right.Item().AlignRight().Text($"Quote No: {quote.Id}").Bold();
                                right.Item().AlignRight().Text($"Date: {quote.CreatedAt.ToLocalTime():dd.MM.yyyy}");
                                right.Item().AlignRight().Text($"Status: {quote.Status}");

                                if (quote.ValidUntil.HasValue)
                                    right.Item().AlignRight().Text($"Valid Until: {quote.ValidUntil.Value:dd.MM.yyyy}");
                            });
                        });

                        column.Item().Text(quote.Title)
                            .FontSize(18)
                            .Bold();

                        if (!string.IsNullOrWhiteSpace(quote.Notes))
                        {
                            column.Item().Text(quote.Notes);
                        }

                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(1);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Element(HeaderCell).Text("Item");
                                header.Cell().Element(HeaderCell).AlignRight().Text("Amount");
                            });

                            table.Cell().Element(BodyCell).Text("Labor Cost");
                            table.Cell().Element(BodyCell).AlignRight().Text($"{quote.LaborCost:N2} TL");

                            table.Cell().Element(BodyCell).Text("Parts Cost");
                            table.Cell().Element(BodyCell).AlignRight().Text($"{quote.PartsCost:N2} TL");

                            table.Cell().Element(BodyCell).Text("Discount");
                            table.Cell().Element(BodyCell).AlignRight().Text($"-{quote.Discount:N2} TL");

                            table.Cell().Element(TotalCell).Text("Total");
                            table.Cell().Element(TotalCell).AlignRight().Text($"{total:N2} TL");
                        });

                        column.Item().PaddingTop(20)
                            .Text("This quote was generated by WorkOrderFlow.")
                            .FontSize(10)
                            .FontColor(Colors.Grey.Darken1);
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated on ");
                        text.Span(DateTime.Now.ToString("dd.MM.yyyy HH:mm"));
                    });
            });
        }).GeneratePdf();
    }

    private static IContainer HeaderCell(IContainer container)
    {
        return container
            .Background(Colors.Grey.Lighten3)
            .Padding(8)
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten1);
    }

    private static IContainer BodyCell(IContainer container)
    {
        return container
            .Padding(8)
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2);
    }

    private static IContainer TotalCell(IContainer container)
    {
        return container
            .Padding(8)
            .Background(Colors.Grey.Lighten4)
            .BorderTop(1)
            .BorderColor(Colors.Grey.Darken1)
            .DefaultTextStyle(x => x.Bold());
    }
}